name: 🚨 Component Error
description: File an issue to report component errors and inaccuracies
title: "[Error] <title>"
labels: "component error"
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for submitting this issue!
        
        _Don't forget to add a title above!_
        
        Please follow guidelines and only submit one issue or pull request per single component.
        
        ---
  - type: checkboxes
    attributes:
      label: Is there an existing issue or pull request for this?
      description: Please search to see if an issue or pull request already exists for this component error.
      options:
        - label: I have searched the existing issues and pull requests
          required: true
  - type: input
    id: component
    attributes:
      label: Component
      description: Use the format 'manufactuer manufactuer_part_number'.
      placeholder: NXP TJA1051T-3
    validations:
      required: true
  - type: dropdown
    id: library_type_labels
    attributes:
      label: Impacted library types
      description: Select all types of library files impacted.
      multiple: true
      options:
        - Symbol
        - Footprint
        - Model (3D)
    validations:
      required: true
  - type: textarea
    id: issue_body
    attributes:
      label: Issue body
      description: Please add any relevant information, such as links to manufacturer documentation.
      render: markdown
      placeholder: |
        Pins 3 and 5 on footprint `TJA1051T_3` are incorrectly swapped.
        See datasheet at https://www.nxp.com/docs/en/data-sheet/TJA1051.pdf.
        ...
    validations:
      required: true
  - type: dropdown
    id: nightly
    attributes:
      label: Has this component been flagged by any other open issues or pull requests?
      description: Please review any open issues and pull requests to avoid duplicates.
      multiple: false
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    id: impact_production
    attributes:
      label: Does this component impact any active production releases?
      description: This information will assist in evaluating the fallout of actively released production designs.
      multiple: false
      options:
        - "Yes"
        - "No"
        - "Unsure, I don't have access to check"
    validations:
      required: true
