name: Component Request
description: File an issue to request adding a new component to the library
title: [Request]: 
labels: component-request
body:
  - type: markdown
    attributes:
      value: |
        > Thank you for submitting this issue!
        > 
        > Please follow guidelines and only submit one issue or pull request per single component.
  - type: input
    id: component
    attributes:
      label: Component
      description: Use the format 'manufactuer manufactuer_part_number'.
      placeholder: NXP TJA1051T-3
    validations:
      required: true
  - type: textarea
    id: issue_body
    attributes:
      label: Issue body
      description: Please add any relevant information, such as links to manufacturer documentation.
      render: markdown
      placeholder: |
        _Example:_
        Requesting new component `TJA1051T_3`.
        Official datasheet found at [NXP TJA1051.pdf](https://www.nxp.com/docs/en/data-sheet/TJA1051.pdf).
        ...
    validations:
      required: true
  - type: dropdown
    id: nightly
    attributes:
      label: Has this component been requested by any other open issues?
      description: Please review any open issues to avoid duplicates.
      multiple: false
      options:
        - Yes
        - No
    validations:
      required: true
