name: 🛎️ Component Request
description: File an issue to request adding a new component to the library
title: "[Request] <title>"
labels: "component request"
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for submitting this issue!
        
        *Don't forget to add a title above!*
        
        Please follow guidelines and only submit one issue or pull request per single component.
  - type: checkboxes
    attributes:
      label: Is there an existing issue or pull request for this?
      description: Please search to see if an issue or pull request already exists for this component request.
      options:
        - label: I have searched the existing issues and pull requests
          required: true
  - type: input
    id: component
    attributes:
      label: Component
      description: Use the format 'manufactuer manufactuer_part_number'.
      placeholder: NXP TJA1051T-3
    validations:
      required: true
  - type: textarea
    id: issue_body
    attributes:
      label: Issue body
      description: Please add any relevant information, such as links to manufacturer documentation.
      placeholder: |
        Requesting new component TJA1051T_3.
        Official datasheet found at https://www.nxp.com/docs/en/data-sheet/TJA1051.pdf.
        ...
    validations:
      required: true
