name: Component Library Issue
about: File an issue to report errors, request new components, and more.
title: "[Library]: "

body:
  - type: markdown
    attributes:
      value: |
        Thank you for filling in this report!
        Please follow guidelines and only submit one issue or pull request per single component.

  - type: labels
    id: issue_type
    attributes:
      label: "Library issue type"
      description: "Select the applicable issue type(s)."
      options:
        - component-request
        - component-error

  - type: labels
    id: library_type_labels
    attributes:
      label: "Impacted library types"
      description: "Select all types of library files impacted."
      options:
        - symbol
        - footprint
        - model

  - type: input
    id: component
    attributes:
      label: "Component"
      description: "Please use this format: 'manufactuer manufactuer_part_number'."
      placeholder: "NXP TJA1051T-3"
    validations:
      required: true

  - type: textarea
    id: issue_body
    attributes:
      label: "Issue body"
      description: "Please add any relevant information, such as links to manufacturer documentation."
      placeholder: |
        _Example:_
        Pins 3 and 5 on footprint `TJA1051T_3` are incorrectly swapped.
        See document at [NXP TJA1051.pdf](https://www.nxp.com/docs/en/data-sheet/TJA1051.pdf).
        ...
    validations:
      required: true

  - type: dropdown
    id: nightly
    attributes:
      label: "Has this component been flagged by any other open issues or pull requests?"
      description: "Please review any open issues and pull requests to avoid duplicates."
      multiple: false
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: dropdown
    id: impact_production
    attributes:
      label: "Does this component impact any active production releases?"
      description: "This information will assist in evaluating the fallout of actively released production designs."
      multiple: false
      options:
        - "Yes"
        - "No"
        - "I don't know"
    validations:
      required: true
