name: Black Formatter

on: [ push, pull_request ]

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Check Black formatting
        run: black --check --line-length 80 .

      - name: Annotate formatting failures
        if: ${{ failure() }}
        run: |
          # Generate diffs and format them as error messages
          diffs=$(black --diff --line-length 80 .)
          echo "$diffs" | while read line; do
            if [[ "$line" =~ would\ reformat\ (.*) ]]; then
              filename=${BASH_REMATCH[1]}
              echo "::error file=$filename::Formatting issues found, see diff for details."
            fi
          done
        shell: bash
