name: Black Formatter

on: [ push, pull_request ]

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Check Black formatting
        run: |
          black --check --line-length 80 . > output.log || echo "::set-output name=black_failed::true"
        id: black_check

      - name: Annotate code
        if: steps.black_check.outputs.black_failed == 'true'
        run: |
          grep -Po 'would reformat \K.*' output.log | while read file; do
            echo "::error file=$file,line=1,col=1::Improper formatting, please reformat."
          done

      - name: Fail workflow
        if: steps.black_check.outputs.black_failed == 'true'
        run: exit 1
