name: Black Formatter

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Check Black formatting
      id: black
      run: |
        black --check --line-length 80 .
      continue-on-error: true

    - name: Annotate formatting issues
      if: failure()
      run: |
        echo "##[error] Some files are not properly formatted. Please run 'black --line-length 80 .' to format your code."
        git diff --name-only | xargs -I {} echo "::error file={}::File needs formatting with Black."
