################################################################################
# check_library.yaml
# Base commit hash: TODO TODO TODO
#
# Check and verify library integrity.
################################################################################

name: Check Library

on: [ push, pull_request ]

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt

      - name: Run script
        run: python .github/workflows/check_symbols.py
