################################################################################
# kibot.yaml
# Base commit hash: TODO TODO TODO
#
# KiBot custom preflight checks and output file automations for GitHub actions.
################################################################################

name: Checks

on:
  push:
    paths:
      - "*.kicad_sch"
      - "*.kicad_pcb"
      - "*.kibot.yaml"
      - ".github/workflows/kibot.yaml"
    branches:
      - main
  pull_request:
    paths:
      - "*.kicad_sch"
      - "*.kicad_pcb"
      - "*.kibot.yaml"
      - ".github/workflows/kibot.yaml"
    branches:
      - main

jobs:
  erc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run ERC
        uses: INTI-CMNB/KiBot@v2_k8
        with:
          # Required - kibot config file
          config: config.kibot.yaml
          # optional - schematic file
          schema: schematic.kicad_sch
          # optional - PCB design file
          board: pcb.kicad_pcb

          dir: Generated
          skip: run_drc
          targets: __NONE__

      - name: Retrieve results
        uses: actions/upload-artifact@v4
        with:
          name: erc_outputs
          path: Generated

  drc:
    runs-on: ubuntu-latest

    needs: erc

    steps:
      - uses: actions/checkout@v4

      - name: Run DRC
        uses: INTI-CMNB/KiBot@v2_k8
        with:
          # Required - kibot config file
          config: config.kibot.yaml
          # optional - schematic file
          schema: schematic.kicad_sch
          # optional - PCB design file
          board: pcb.kicad_pcb

          dir: Generated
          skip: run_erc
          targets: __NONE__

      - name: Retrieve results
        uses: actions/upload-artifact@v4
        with:
          name: drc_outputs
          path: Generated

  var_default:
    name: Default variant

    runs-on: ubuntu-latest

    needs: [ erc, drc ]

    steps:
      - uses: actions/checkout@v4

      - uses: INTI-CMNB/KiBot@v2_k8
        with:
          # Required - kibot config file
          config: config.kibot.yaml
          # optional - schematic file
          schema: schematic.kicad_sch
          # optional - PCB design file
          board: pcb.kicad_pcb

          dir: default
          variant: default
          skip: run_erc,run_drc

      - name: upload results
        uses: actions/upload-artifact@v4
        with:
          name: default_variant
          path: default
